server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@task-desafio.qousaqi.mongodb.net/tasks?retryWrites=true&w=majority&appName=task-desafio
  webflux:
    base-path: /task-api

